spring:
  application:
    name: payment-aggregation-service

  datasource:
    url: jdbc:postgresql://localhost:5435/payment_db
    username: ${DB_USERNAME:payment_user}
    password: ${DB_PASSWORD:payment_pass}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate  # Flyway handles schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    dev.tengiz.payment: DEBUG
    org.springframework.web: DEBUG
